# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      # Runs a single command using the runners shell
      - name: Run jacocoTest for Code Coverage
        run: ./gradlew test jacocoTestReport
        
      - name: 'Publish jococoResult.xml'
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: jacocoTestReport.xml
          path: ./build/reports/jacoco/test/jacocoTestReport.xml
        
          
      # Runs a single command using the runners shell
      - name: Check that code coverage met the defined limit
        run: ./gradlew test jacocoTestCoverageVerification

          
      # Runs a single command using the runners shell
      - name: Built and test project
        run: ./gradlew clean build
      - name: 'Publish Test Report'
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: 'test-report'
          path: /build/reports/test/test/*
        
  sonarcloud:
    if: always()
    needs: [build_and_test,dependency-check]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Download JococoTestReportArtifact
      uses: actions/download-artifact@v2
      with:
        name: jacocoTestReport.xml
        path: /build/reports/jacoco/test/jacocoTestReport.xml
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  dependency-check:
    if: always()
    needs: [build_and_test]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: OWASP checker
        run: ./gradlew --stacktrace dependencyCheckAnalyze
    
      - name: Backup OWASP Report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report.html
          path: ./build/reports/dependency-check-report.html
          
    
