# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths-ignore:
      -'**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  test:
    if: always()
    needs: [dependency-check]  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      # Runs a single command using the runners shell
      - name: Run jacocoTest for Code Coverage
        run: ./gradlew test jacocoTestReport
        
      - name: 'Publish jococoResult.xml'
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: jacocoTestReport.xml
          path: ./build/reports/jacoco/test/jacocoTestReport.xml
        
          
      # Runs a single command using the runners shell
      - name: Check that code coverage met the defined limit
        run: ./gradlew test jacocoTestCoverageVerification

          
      # Runs a single command using the runners shell
      - name: Test project
        run: ./gradlew test
      - name: 'Publish Test Report'
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: 'test-report'
          path: ./build/reports/tests/test/
          
      - name: 'Publish Test Results in xml format'
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: testresults.xml
          path: ./build/test-results/test/*.xml
          if-no-files-found: warn # 'warn' or 'ignore' are also available, defaults to `warn` 

        
  sonarcloud:
    if: always()
    needs: [test,dependency-check]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Download JococoTestReportArtifact
      uses: actions/download-artifact@v2
      with:
        name: jacocoTestReport.xml
        path: ./build/reports/jacoco/test/
        
    - name: Download TestResultArtifact
      uses: actions/download-artifact@v2
      with:
        name: testresults.xml
        path: ./build/test-results/test/
        
    - name: Download OWASP Dependency Check Results
      uses: actions/download-artifact@v2
      with:
        name: dependency-check-reports
        path: ./build/reports/
        
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  dependency-check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: OWASP checker
        run: ./gradlew --stacktrace dependencyCheckAnalyze
    
      - name: OWASP Report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-reports
          path: ./build/reports/
          
  build:
    if: always()
    needs: [dependency-check,sonarcloud,test]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2      
      # Runs a single command using the runners shell
      - name: Built the project
        run: ./gradlew clean build 
